apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeevents
  namespace: kubeevents
  labels:
    app.kubernetes.io/name: kubeevents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeevents
  labels:
    app.kubernetes.io/name: kubeevents
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeevents
  labels:
    app.kubernetes.io/name: kubeevents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeevents
subjects:
  - kind: ServiceAccount
    name: kubeevents
    namespace: kubeevents
